[features]
seeds = false
[programs.devnet]
magic_hat = "9uX5aejHzv5nCc7pAZCBRkyLe8RKdHh225DxWpkKHx6h"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abstracted/solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
