[features]
seeds = false
[programs.devnet]
magic_hat = "C52UybC2ucG3BaJY2JRKi1aNZFyJ3iMh82qv8shxqynS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/home/abstracted/solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
